# Generated by Django 2.2.11 on 2020-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmoment",
            name="klant",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar een KLANT (in Klanten API) indien de klantinteractie niet anoniem is.",
                max_length=1000,
            ),
        ),
    ]
