# Generated by Django 2.2.11 on 2020-06-12 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0002_auto_20200525_1024"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmoment",
            name="interactiedatum",
        ),
        migrations.AddField(
            model_name="contactmoment",
            name="registratiedatum",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="De datum en het tijdstip waarop het CONTACTMOMENT is geregistreerd.",
            ),
        ),
    ]
