# Generated by Django 2.2.11 on 2020-06-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0003_contactmoment_voorkeurstaal"),
        ("datamodel", "0003_contactmoment_vorig_contactmoment"),
    ]

    operations = []
