# Generated by Django 2.2.11 on 2020-07-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0004_merge_20200626_0757"),
        ("datamodel", "0004_merge_20200619_1118"),
    ]

    operations = []
