# Generated by Django 2.2.11 on 2020-06-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0003_auto_20200612_1359"),
        ("datamodel", "0004_merge_20200619_1118"),
    ]

    operations = []
