# Generated by Django 2.2.11 on 2020-07-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0005_merge_20200709_1613"),
        ("datamodel", "0005_merge_20200619_1130"),
    ]

    operations = []
