# Generated by Django 2.2.14 on 2020-10-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0006_merge_20200709_1630"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmoment",
            name="klant",
        ),
    ]
